### ISSUE TITLE
いまさら clearfix を考える

### ISSUE THREAD

**Issue by shikakun** [shikakun/tips#3]
`float: left;` とかで `display: block;` な要素を横に並べたりするとき、そのままだと親の要素の高さが無視されちゃったりして表示が崩れるので、 `float: left;` してる要素をまとめてる要素に `.clearfix` とかいうクラス名で下記のような CSS をあてることがある。

``` CSS
.clear {
  zoom: 1;
}

.clear:after {
  content: "";
  display: block;
  clear: both;
}
```

なんも深く考えずにこういうもんだろと思って使ってきたけど、一体これってなんなんだろう。人はいつ clearfix を知るんだろう？
#### そもそも何が問題なのか？

float プロパティを指定してる要素はページから浮いてるので、本来あるはずだったページのなかの配置の決まりから外れてしまう。
なにしろ「浮いて」しまっているので、親の要素も float してる要素の高さを把握できない！

実は float のそうした性質を解消するために clear っていうプロパティもあるんだけど、

``` HTML
<br class="clear">
```

``` CSS
.clear {
  clear: both;
}
```

float した要素のあとにわざわざ不要なタグなんか書いてられるか！というわけで広まったのが clearfix と呼ばれるブラウザのバグを突いたハックだったと。

要するに `.clearfix` と指定した要素のあとに `clear: both;` な疑似要素を付け足してるということだったんですね。
#### 参考

clearfix の歴史についてはわかりやすくまとまったページがありました。
- http://kojika17.com/2013/06/clearfix-2013.html

このページを読んでると、そもそも float を利用してレイアウトしてること自体が仕様のハックなんだなあ… と思えてきます。
早く `display: flex;` みたいな指定で横に並ぶ未来がくるといいですね。
