### ISSUE TITLE
placeholder のスタイルシートを指定する

### ISSUE THREAD

**Issue by shikakun** [shikakun/tips#63]
各ベンダープレフィックスは以下のように書けば指定できる。

``` css
::-webkit-input-placeholder { color: red; }
:-moz-placeholder { color: red; }
::-moz-placeholder { color: red; }
:-ms-input-placeholder { color: red; }
```

こうやってプロパティを1個にまとめて書くと効かない！

``` css
/* これは指定があたらない */
::-webkit-input-placeholder,
:-moz-placeholder,
::-moz-placeholder,
:-ms-input-placeholder {
   color: red;
}
```

`:-moz-*` のコロンひとつは Firefox 18 まで、Firefox 19 以降は `::-moz-*` でコロンふたつの指定になった。Firefox 19 以降では、コロンひとつでもふたつとして解釈してくれるらしい。
#### 参考
- http://css-tricks.com/snippets/css/style-placeholder-text/
- http://myakura.hatenablog.com/entry/2012/11/26/224834

**Comment by shikakun** [comment]
scss でこうやって書いたけど、

``` css
%placeholder {
  color: #ccc;
  font-weight: normal;
}

::-webkit-input-placeholder { @extend %placeholder; }
:-moz-placeholder { @extend %placeholder; }
::-moz-placeholder { @extend %placeholder; }
:-ms-input-placeholder { @extend %placeholder; }
```

compressed したら、こう出力されちゃったので便利だけどだめだった！

``` css
::-webkit-input-placeholder,:-moz-placeholder,::-moz-placeholder,:-ms-input-placeholder {
    color: #ccc;
    font-weight: normal
}
```
